version: '2'

services:
  default:
    image: django_project:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: default
    volumes:
    - ./../../shared:/shared
    ports:
      - 8000:8000
    env_file:
      - ./deploy/config.sh
