---
kind: pipeline
name: test-java-mvnw

platform:
  os: linux
  arch: amd64

steps:
- name: test-java-mvnw
  image: loanstreet-ubuntu-19.04/java:8
  volumes:
  - name: ssh
    path: /root/.ssh
  - name: maven
    path: /root/.m2
  commands:
  - service ssh start
  - sh ./tests/java.sh

volumes:
- name: ssh
  host:
    path: /root/.ssh
- name: maven
  host:
    path: /dronetmp/m2

---
kind: pipeline
name: test-rails

platform:
  os: linux
  arch: amd64

steps:
- name: test-rails
  image: loanstreet-ubuntu-19.04/ruby:2.5
  volumes:
  - name: ssh
    path: /root/.ssh
  - name: bundler
    path: /drone/bundler
  commands:
  - ln -sf /drone/bundler /tmp/bundle
  - service ssh start
  - sh ./tests/rails.sh


volumes:
- name: ssh
  host:
    path: /root/.ssh
- name: bundler
  host:
    path: /dronetmp/ruby-2.5.3/bundle

---
kind: pipeline
name: test-django

platform:
  os: linux
  arch: amd64

steps:
- name: test-django
  image: loanstreet-ubuntu-20.04/python:3.7
  volumes:
  - name: ssh
    path: /root/.ssh
  commands:
  - service ssh start
  - sh ./tests/django.sh


volumes:
- name: ssh
  host:
    path: /root/.ssh
#
# ---
# kind: pipeline
# name: test-reactjs

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: test-reactjs
#   image: loanstreet-ubuntu-20.04/node:13
#   volumes:
#   - name: ssh
#     path: /root/.ssh
#   - name: tmpdir
#     path: /tmp/phantomjs
#   commands:
#   - . ~/.profile
#   - service ssh start
#   - sh ./tests/reactjs.sh


# volumes:
# - name: ssh
#   host:
#     path: /root/.ssh
# - name: tmpdir
#   host:
#     path: /dronetmp/tmp
...