version: '2'

services:
  default:
    image: rails_project:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: default
    volumes:
      - ./../../shared:/shared
    ports:
      - 3000:80
    env_file:
      - ./config/deploy/config.sh
